server:
  port: 9000
spring:
  application:
    name: easydemo
# xxl-job配置
xxl:
  job:
    admin:
      # xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8080/xxl-job-admin
    # xxl-job, access token
    accessToken: default_token
    executor:
      appname: xxl-job-executor-easydemo # xxl-job executor appname
      address: # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      ip:  # xxl-job executor server-info
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler # xxl-job executor log-path
      logretentiondays: 30 # xxl-job executor log-retention-days